version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=fuelguard
      - DOCKER_INFLUXDB_INIT_BUCKET=fuelguard
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
  
  gateway:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=fuelguard
    depends_on:
      - redis
      - influxdb
    command: uvicorn gateway.api:app --host 0.0.0.0 --port 8000 --reload
  
  simulator:
    build: .
    environment:
      - API_URL=http://gateway:8000
    depends_on:
      - gateway
    command: python -m simulator.sensor_simulator --multi --interval 3

volumes:
  influxdb-data: